"""
- Adds access_roles column
- Adds access_tiers column

Revision ID: 017c4b1756e1
Revises: 3299ad375790
Create Date: 2020-03-28 00:33:17.978190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '017c4b1756e1'
down_revision = '3299ad375790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('access_roles', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('configurations', sa.Column('access_tiers', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurations', 'access_tiers')
    op.drop_column('configurations', 'access_roles')
    # ### end Alembic commands ###
