"""
Adds configurations table
Adds organizations table

Revision ID: 2e70e47d57e6
Revises: 3b1fd9e601b2
Create Date: 2020-03-20 18:04:19.316434

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2e70e47d57e6'
down_revision = '3b1fd9e601b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('access_control_type',
                              sa.Enum('STANDARD_ACCESS_CONTROL', 'TIERED_ACCESS_CONTROL', name='accesscontroltype'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('organizations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
