"""Renames organization_id foreign key to parent_organization_id

Revision ID: 3299ad375790
Revises: 6bde57c7cbc3
Create Date: 2020-03-27 16:55:19.854796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3299ad375790'
down_revision = '6bde57c7cbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_organization_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['parent_organization_id'], ['id'])
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'parent_organization_id')
    # ### end Alembic commands ###
