"""Adds mailer settings column.
Revision ID: 333494146438
Revises: 34d54c413880
Create Date: 2020-03-31 12:09:20.153723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '333494146438'
down_revision = '34d54c413880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('_mailer_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurations', '_mailer_settings')
    # ### end Alembic commands ###
