"""
Reverts _identification to nullable,
Adds _role attributes.

Revision ID: 3b1fd9e601b2
Revises: ec6ce6213700
Create Date: 2020-03-20 17:55:31.399087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b1fd9e601b2'
down_revision = 'ec6ce6213700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_role', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('users', '_identification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_identification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('users', '_role')
    # ### end Alembic commands ###
