"""Adds index and constraint to make sure emails are unique

Revision ID: 50884930bc8e
Revises: 592fbf68ac80
Create Date: 2020-04-02 11:15:48.607861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50884930bc8e'
down_revision = '592fbf68ac80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
