"""Creates initials tables

Revision ID: 5546a634cce0
Revises:
Create Date: 2020-05-03 23:01:38.761869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5546a634cce0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklisted_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("is_master", sa.Boolean(), nullable=True),
        sa.Column("public_identifier", sa.String(length=8), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_is_master"), "organizations", ["is_master"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_public_identifier"),
        "organizations",
        ["public_identifier"],
        unique=True,
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("given_names", sa.String(length=35), nullable=False),
        sa.Column("surname", sa.String(length=35), nullable=False),
        sa.Column(
            "_identification", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(length=13), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("password_hash", sa.String(length=200), nullable=True),
        sa.Column("_otp_secret", sa.String(length=200), nullable=True),
        sa.Column("is_activated", sa.Boolean(), nullable=True),
        sa.Column(
            "signup_method",
            sa.Enum("WEB_SIGNUP", "MOBILE_SIGNUP", name="signupmethod"),
            nullable=True,
        ),
        sa.Column(
            "password_reset_tokens", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("parent_organization_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_organization_id"], ["organizations.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_organizations_public_identifier"), table_name="organizations"
    )
    op.drop_index(op.f("ix_organizations_is_master"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_table("blacklisted_tokens")
    # ### end Alembic commands ###
