"""Creates user with primary attributes

Revision ID: 76c697dd029d
Revises: 
Create Date: 2020-03-18 10:54:12.306319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76c697dd029d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('given_names', sa.String(length=35), nullable=False),
    sa.Column('surname', sa.String(length=35), nullable=False),
    sa.Column('identification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('msisdn', sa.String(length=13), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_msisdn'), 'users', ['msisdn'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_msisdn'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
