"""Add transactions table

Revision ID: 7a80c38cb8e7
Revises: 5b369778c622
Create Date: 2020-07-24 10:47:45.633294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a80c38cb8e7'
down_revision = '5b369778c622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(precision=2), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('service_provider_transaction_reference', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETE', 'FAILED', 'INITIATED', 'PENDING', name='transactionstatus'), nullable=True),
    sa.Column('type', sa.Enum('BUSINESS_TO_BUSINESS', 'BUSINESS_TO_CONSUMER', 'MOBILE_CHECKOUT', name='transactiontype'), nullable=True),
    sa.Column('service_provider', sa.Enum('AFRICAS_TALKING', 'DARAJA', name='transactionserviceprovider'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_phone'), 'transactions', ['phone'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_service_provider_transaction_reference'), 'transactions', ['service_provider_transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_service_provider_transaction_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_phone'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
