"""
Adds password_reset_tokens column to users.

Revision ID: bb9a467b56b8
Revises: 099c52fd3142
Create Date: 2020-04-12 00:42:16.951253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb9a467b56b8'
down_revision = '099c52fd3142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_tokens', postgresql.ARRAY(sa.String()), default=[], nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_tokens')
    # ### end Alembic commands ###
