"""
- Made  identification non-nullable
- Adds otp_secret
- Adds check of activated user
- Adds check sign_up_method

Revision ID: ec6ce6213700
Revises: b8abe318cc4b
Create Date: 2020-03-19 15:41:13.761525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec6ce6213700'
down_revision = 'b8abe318cc4b'
branch_labels = None
depends_on = None

signup_method = sa.Enum('WEB_SIGNUP', 'MOBILE_SIGNUP', name='signupmethod')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_otp_secret', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), nullable=True))

    signup_method.create(op.get_bind(), checkfirst=False)
    op.add_column('users', sa.Column('signup_method', signup_method, nullable=True))
    op.execute('ALTER TABLE users ALTER COLUMN signup_method TYPE signupmethod USING signup_method::text::signupmethod')

    op.alter_column('users', '_identification',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_identification',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True)
    op.drop_column('users', 'signup_method')
    signup_method.drop(op.get_bind(), checkfirst=False)
    op.drop_column('users', 'is_activated')
    op.drop_column('users', '_otp_secret')
    # ### end Alembic commands ###
