"""Adds check for master organizations

Revision ID: fab4b86ff429
Revises: 017c4b1756e1
Create Date: 2020-03-29 10:36:27.172273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab4b86ff429'
down_revision = '017c4b1756e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_master', sa.Boolean(), default=False, nullable=True))
    op.create_index(op.f('ix_organizations_is_master'), 'organizations', ['is_master'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_is_master'), table_name='organizations')
    op.drop_column('organizations', 'is_master')
    # ### end Alembic commands ###
